#python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_mse_0.05' --test_iters 200000 --batch_size 1 --attack_loss='mse' --attack_budget=0.05
#python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_mse_0.025' --test_iters 200000 --batch_size 1 --attack_loss='mse' --attack_budget=0.025
#python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_negtv_0.05' --test_iters 200000 --batch_size 1 --attack_loss='negtv' --attack_budget=0.05
#python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_negtv_0.025' --test_iters 200000 --batch_size 1 --attack_loss='negtv' --attack_budget=0.025
#python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_tv_0.05' --test_iters 200000 --batch_size 1 --attack_loss='tv' --attack_budget=0.05
#python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_tv_0.025' --test_iters 200000 --batch_size 1 --attack_loss='tv' --attack_budget=0.025

python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_brisque_0.05' --test_iters 200000 --batch_size 1 --attack_loss='brisque' --attack_budget=0.05
python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_brisque_0.025' --test_iters 200000 --batch_size 1 --attack_loss='brisque' --attack_budget=0.025
python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_negbrisque_0.05' --test_iters 200000 --batch_size 1 --attack_loss='negbrisque' --attack_budget=0.05
python main.py --mode test --dataset CelebA --image_size 256 --c_dim 5 --selected_attrs Black_Hair Blond_Hair Brown_Hair Male Young --model_save_dir='stargan_celeba_256/models' --result_dir='stargan_celeba_256/results_test_negbrisque_0.025' --test_iters 200000 --batch_size 1 --attack_loss='negbrisque' --attack_budget=0.025
